### ISSUE TITLE
[BUG] Config Resets when starting game.

### ISSUE THREAD

**Issue by Supertacoz** [RedPxnda/RespawnObelisks#10]
**Describe the bug**
Whenever I launch Minecraft with this mod installed, the config will always reset itself to it's default state. (and yes, I am saving the file before closing it.)

**To Reproduce**
1. install mod
2. start game once.
3. close game, modify config
4. start game again, and see that options have been reset to default.

**Expected behavior**
I expected my changes to be kept. 

**Versions**
 mod version: 2.4-c
game version: 1.20.1
forge version: 47.2.17
architectury: 9.1.12 forge
balm version: 7.1.2 forge

**Additional notes**
I am using the modrinth app, though that should make any difference.

**Comment by RedPxnda** [comment]
Are you sure there are no errors in the config? Usually this may happen if you make a mistake. 
I use the ResourcefulConfig library for my configs, if there is an issue it's probably more in there. 
I've never had this issue before, in both my experiences and others'. Are the mod versions you've listed there the only mods you have?

And it doesn't matter the value you change? Any change causes a reset?

**Comment by Supertacoz** [comment]
It is possible I made errors when editing the config. 
I have a number of other mods, but they shouldn't be affecting the config. 
I will further test when I get back home.

**Comment by Supertacoz** [comment]
Yeah I messed up when editing the config. sorry.
