### ISSUE TITLE
[BUG] Tethered enchant config both refers to tethered as obeliskbound and does nothing

### ISSUE THREAD

**Issue by Nicodemus111** [RedPxnda/RespawnObelisks#13]
**Describe the bug**
Changing any setting for the tethered enchant does nothing, you cannot turn off the enchant or make it a non treasure enchant.

**To Reproduce**
1. Change any setting in the config for tethered
2. Check if the change applied (easiest with apotheosis)

**Expected behavior**
Changing the setting should work ingame

**Screenshots**
![image](https://github.com/RedPxnda/RespawnObelisks/assets/96658552/63d58862-ddc2-44dc-be15-a0854f8bc8c5)
![image](https://github.com/RedPxnda/RespawnObelisks/assets/96658552/62f90329-aa99-4af0-9609-b505680221ed)

**Versions**
 - 2.4-d (probably broke when the name was changed)
 - 1.21.1-47.1.3

**Comment by Nicodemus111** [comment]
(it says level.0 in the tooltip since i set the max level to 0 to test)

**Comment by RedPxnda** [comment]
![image](https://github.com/RedPxnda/RespawnObelisks/assets/54185270/3afe6f48-ea43-4733-a121-1a323ea5c297)
Apotheosis overrides the values of enchantments, including the things you mentioned.
Are you sure this happens without apotheosis, or if you instead disable those values through apotheosis's enchantment config?
And also, disabling the enchantment doesn't actually remove it from the game. It just makes it unobtainable(by overriding the treasure, tradeable, etc. values to be false).

**Comment by Nicodemus111** [comment]
Oh I forgot about apotheosis enchantment settings, disabling it in there fixed it.
