### ISSUE TITLE
[Suggestion] Config option for Lodestone / Beacon range from Obelisk

### ISSUE THREAD

**Issue by Ado-line** [RedPxnda/RespawnObelisks#14]
**Problem:**
Having two Obelisks if you want one to teleport to and one with infinite charge seems impossible without making the infinite block the Lodestone. (Or even just one with both)

**Ideal:**
A config option to allow the Lodestone and Beacon to be farther under the Obelisk so they can both coexist, having this and the option listed in the section below seems like a good idea as well. The config option for the distance could be something like "Max Distance Below"

**Alternative:**
Config option to allow teleportation to an Obelisk without it being your respawn point

**Context:**
Currently I'm on Minecraft 1.19.2, as this is the version I'm making my modpack for. I'd greatly appreciate it, if this is implemented, that it also be back-ported to 1.19.2. I totally understand if not however, as your FAQ states you don't do back-ports.

Using KubeJS I added the Lodestone to the Beacon base blocks tag, so I thought I could have both a recall Obelisk and an infinite charge one if I put the Lodestone beneath the Beacon, but nope, no dice. I also tried with the Lodestone above the Beacon and that doesn't work either. Below I have some examples of what could be possible:
||||
|---|---|---|
|![Artboard 1 copy 2](https://github.com/RedPxnda/RespawnObelisks/assets/11416064/83c8cbab-15ec-4b26-ac45-e255202bd610)|![Artboard 1](https://github.com/RedPxnda/RespawnObelisks/assets/11416064/43667cec-3902-4957-9205-655596560acd)|![Artboard 1 copy](https://github.com/RedPxnda/RespawnObelisks/assets/11416064/b7f2bb86-3c40-499a-b6cb-58a810768340)|

All Figures: Without changes to the Lodestone to allow it to be a Beacon base block, or to allow it to be transparent to Beacons, these setups don't work, except for Fig. B, if you want the beacon to be active.

Figure A: This is specifically what I tried to do, after making the Lodestone a base block via KubeJS, obviously the Beacon doesn't need to be active for the Obelisk to consider it an infinite charge supply, but I was hoping to still have an active Beacon as well.

Figure B: This is likely what anyone who doesn't modify the Lodestone would do if they wanted both functionalities and an active Beacon

Figure C: Another example of having them both, as mentioned above, the Lodestone would need to be made transparent for the Beacon, but this setup would at least provide infinite charge as well as teleportation

**Comment by RedPxnda** [comment]
You can configure the valid infinite charge blocks to include the lodestone too. (It should allow a list of blocks or block tags)
It is intentional that you can't have both an infinite charge and teleporting obelisk. The idea is that teleportation comes at a cost, and being able to teleport infinitely feels overpowered. 
Although, this is a good idea and I also enjoy the idea of potentially requiring the beacon to be active, so this is on the todo list.

**Comment by RedPxnda** [comment]
In 2.5, you will be able to change the blocks you can bind a recovery compass to. Specifically, you can add beacons as a block to bind and do that.
There is also now a config option for required beacon power level.
