### ISSUE TITLE
[1.19.2] Ability to use the vanilla bed to skip the night (But without set the spawn point)

### ISSUE THREAD

**Issue by SigmaFlame** [RedPxnda/RespawnObelisks#15]
Hello,

**Is your feature request related to a problem? Please describe.**
With your mod installed, the player can't sleep so he can't low the phantoms spawn.

**Describe the solution you'd like**
A way to sleep in the bed in order to skip the night, but without changing the spawn point.

Thanks in advance.

**Comment by RedPxnda** [comment]
This mod does not prevent the user from sleeping in bed. This must be an incompatibility. What other mods do you have?

**Comment by RedPxnda** [comment]
Going to close as I cannot replicate and OP is inactive. Feel free to reopen.
