### ISSUE TITLE
Mohist Server Does Not Start

### ISSUE THREAD

**Issue by Skulexander** [RedPxnda/RespawnObelisks#16]
I was trying to get a Mohist server running with this mod installed, but the server does not start. When I remove this mod, and only this mod, the server starts. [Here](https://pastebin.com/dKE8YGKj) is the crash report.

**Comment by RedPxnda** [comment]
I cannot provide support for Mohist. It’s sketchy, unofficial, and doesn’t work with plenty of other mods. Sorry.
