### ISSUE TITLE
[BUG] Server side mod breaks all restart funtions 2.5 version

### ISSUE THREAD

**Issue by Joshernoob** [RedPxnda/RespawnObelisks#17]
**Describe the bug**
When version 2.5 a-c are installed serverside the mod will load perfectly but on reload or shutdown it hangs forever on Unloading configs type SERVER

**To Reproduce**
1. Have server up with mod and needed core mods installed
2. run server on newest forge version as of typing this (47.2.32)
3. reload after it finishes world creation or turn server off

**Expected behavior**
server should restart and turn off as normal

**Screenshots**
N/A not posssable as the server now running the full modpack i planned to use this mod in

**Versions**
 - 2.5-a-c
 - Forge Version 47.2.32
 - Architectury API version: architectury-9.2.14 , Resourceful Config version: resourcefulconfig-forge-1.20.1-2.1.2

**Additional notes**
I backtracked to 2.4-d and that stopped the bug but ended up preventing me from respawning to an obelisk at all when trying

**Comment by RedPxnda** [comment]
Far from home right now, do you mind sending the logs so I could have a quick look?

**Comment by Joshernoob** [comment]
> Far from home right now, do you mind sending the logs so I could have a quick look?

I can send the full .log or a pastbin, pastbin may be only parts and bits

**Comment by Joshernoob** [comment]
[debug-5.log](https://github.com/RedPxnda/RespawnObelisks/files/15284756/debug-5.log)

Think this may help more then any of the others, its the debug.log of changing from 2.5-a to 2.5-c with only 4 other mod installed not incuding cores as at this point i was testing the versions

**Comment by RedPxnda** [comment]
The latest.log is more the thing I need, at least after the stalling happens.

**Comment by Joshernoob** [comment]
that may take awile to fine with how many .gz logs i have to go threw to find the one thats a test log

**Comment by RedPxnda** [comment]
There should always be one "latest.log", if you can sort alphabetically that should help.

**Comment by Joshernoob** [comment]
![Screenshot 2024-05-11 220149](https://github.com/RedPxnda/RespawnObelisks/assets/64944433/2e80f7dc-1e21-404a-b7e3-7aaba2eb1f25)
![Screenshot 2024-05-11 220109](https://github.com/RedPxnda/RespawnObelisks/assets/64944433/929c8ec4-6efc-4a50-bd78-9067d6ec3c12)
[latest.log](https://github.com/RedPxnda/RespawnObelisks/files/15284808/latest.log)


Ended up remaking the error to get the log for you and took some screenshots whiel i was at it

**Comment by RedPxnda** [comment]
Odd, I really don’t see anything in that log. I’ll take a look later today.

**Comment by Joshernoob** [comment]
just saw this,

i did't as well that why I had to go threw and remove mods until I found it was this one

**Comment by Joshernoob** [comment]
just the 2 mods seems it works fine my guess is its an addon?

**Comment by Joshernoob** [comment]
only 2 mods work is false that was meant for a diffrent mods report sorry about that

**Comment by RedPxnda** [comment]
Not necessarily important, but resourceful config isn’t required as of 2.5. Not sure if that will help.

**Comment by Joshernoob** [comment]
> Not necessarily important, but resourceful config isn’t required as of 2.5. Not sure if that will help.
no way for me to test at this point in time the server i have up is being used and can't be taken down again

**Comment by RedPxnda** [comment]
I'm afraid I'm not able to replicate this issue. I've booted up a server with just the mod and its dependencies, ran reload, and it reloaded perfectly without error. Same steps in your case?
Actually, I did realize, latest forge isn't supported, and I didn't test with that. The newer MinecraftForge versions have made some breaking changes, I'm not sure if those are present in that specific version, but I can't guarantee support for newer versions. I tested 4.2.20 and it worked fine, 4.2.32 should be fine but that's something to consider. Forge has been split into MinecraftForge and NeoForge, and I am supporting NeoForge rather than MinecraftForge.(~4.1.something is the last version with parity, iirc)

**Comment by Joshernoob** [comment]
currently using the forge version for the pack and 4.2.32 doesn't seem to work, at least on my end,since you move to neoforge i guess it make since ithat the newer forge version oare not saported, sad to see though since the mod will have be be removed since mods in my pack need  4.2.30 or up and are cross combat on 1.20.1

**Comment by RedPxnda** [comment]
Could not replicate, going to close for now but feel free to reopen.
