### ISSUE TITLE
[BUG] Apparent incompatability with Origins (Fabric)

### ISSUE THREAD

**Issue by Xaegrek** [RedPxnda/RespawnObelisks#18]
**Describe the bug**
For Minecraft 1.20.1, with Fabric and Origins installed, respawning to an obelisk fails with the chat message "You have no home respawn point or charged respawn obelisk, or it was obstructed".  The charge of the obelisk is also deducted as if it worked correctly

**To Reproduce**
1. Set respawn point to a charged obelisk
2. execute /kill 
3. Respawn at world spawn with chat message. Obelisk charge also reduced

**Expected behavior**
Respawn at obelisk

**Screenshots**
![2024-05-15_19 39 25](https://github.com/RedPxnda/RespawnObelisks/assets/5533899/4a6a4fa7-9606-4a14-8dc6-3082b56edbee)

**Versions**
 - Respawn Obelisk Version: 2.5-c
 - Fabric Loader Version (if fabric): 0.15.10
 - Fabric API Version (if fabric): 0.92.1 + 1.20.1
 - Architectury API version: 9,2,13
 - Origins: 1.10.0

**Additional notes**
It's unclear to me if this is actually related to RespawnObelisk, or Origins. The mod's function as expected in Forge, so it could be an issue with how Fabric handles something.

**Comment by RedPxnda** [comment]
I feel like this issue has been reported on my discord before. If I remember correctly it’s on Origins’ side- I believe they use a redirect mixin which is incredibly bad for compat to make their blaze origin respawn in the nether, but I’m not entirely sure. I will have to double check. (Redirect mixins pretty much override a call entirely, and won’t work with other mods that try to mixin to the same place. The alternative is MixinExtra’s WrapOperation, which is now incorporated into Fabric Mixin itself.)

**Comment by RedPxnda** [comment]
Not something I can fix. Feel free to reopen if necessary.
