### ISSUE TITLE
[Suggestion] Rename Enchantment

### ISSUE THREAD

**Issue by SaltSouls** [RedPxnda/RespawnObelisks#2]
I like the idea of the obeliskbound enchantment, but find then name to be a bit cumbersome and awkward. What would you say to something along the lines of anchored/tethered instead of the  current enchantment name? Kinda gives the impression that the item is tied to the obelisk without sounding as awkward as it currently does.

**Comment by RedPxnda** [comment]
That's fair. I do agree, and tethered is certainly a better name. I'll add this in the next update, or if you make a pr I could merge it whenever.

**Comment by RedPxnda** [comment]
Added in 2.4
