### ISSUE TITLE
Sleeping at a bed resets spawnpoint

### ISSUE THREAD

**Issue by fennecr** [RedPxnda/RespawnObelisks#3]
When a player has their spawn set at an obelisk, and then sleeps to skip the night, their spawnpoint is set to the bed and then removed, causing them to respawn at worldspawn instead of their obelisk.

**Comment by RedPxnda** [comment]
What other mods do you have installed? Do you have Dusk by someaddon perchance?

**Comment by fennecr** [comment]
No, I do not have dusk installed. I do have the mod Day Dream installed, but would that affect anything?

**Comment by RedPxnda** [comment]
That's odd. This is something I'll have to look into, I'll do some testing tomorrow and get back to you.

**Comment by RedPxnda** [comment]
Sorry I got back to you so late. I can't seem to reproduce this.... does this happen when only Respawn Obelisks is installed?

**Comment by fennecr** [comment]
Yes, though now I'm suspecting it might be PolySit, something in the latest
patch notes mentions vanilla bed mechanics. I'll see if updating that fixes
the issue ASAP.

**Comment by RedPxnda** [comment]
Any update?

**Comment by fennecr** [comment]
Sorry! I completely forgot about this. Some players are saying they can set their spawns if the shift+right click a bed without armor or something? I will be doing more thorough testing soon.

**Comment by fennecr** [comment]
Honestly, I'm not sure what it is. I'm running this mod in a server environment and some players are able to set their spawns but the circumstances are always different, sometimes it slips through and sets their spawn, sometimes it doesn't. Testing just day dream and respawn obelisks didn't lead to anything.

**Comment by RedPxnda** [comment]
Such a weird issue. I want to help but I don't really know how

**Comment by fennecr** [comment]
Nevermind, actually! I was reading back and realized I forgot to test just PolySit and Respawn Obelisks. Shift+clicking with polysit installed causes it to set your spawn. I will likely just remove polysit to fix this issue, unless there's anything that can be done on this end.

**Comment by fennecr** [comment]
Yeah, any other sit mod fixes this issue for me, so this wasn't related to this mod after all. Sorry for wasting your time!
