### ISSUE TITLE
[Suggestions] Config to allow obelisks in certain dimensions

### ISSUE THREAD

**Issue by grundyboy34** [RedPxnda/RespawnObelisks#4]
Would love to see the ability to allow the obelisks to be used in modded dimensions
Perhaps each obelisk could have a strict blacklist of dimensions it's not allowed in? 
For example:
Overworld: nether, the_end
Nether: overworld, the_end
End: overworld, nether

If the obelisk is activated and the dimension isn't in the blacklist, then it's allowed.

**Comment by RedPxnda** [comment]
Well, I want the default behavior to be more a whitelist of dimensions, so I guess I could add 2 config options (per dimension): first being whitelist for allowed dimensions, second being whether it should act as a blacklist or not.

**Comment by RedPxnda** [comment]
![image](https://github.com/RedPxnda/RespawnObelisks/assets/54185270/df2239c3-c5cb-4451-9ed4-ae60577305f4)
Added in 2.4
