### ISSUE TITLE
[Bug] Dedi server, changing infinite charge block causes it to always be infinite charge (no matter the block underneath)

### ISSUE THREAD

**Issue by grundyboy34** [RedPxnda/RespawnObelisks#5]
Steps to reproduce (on dedicated server):
1) Change infinite charge block to "minecraft:lodestone"
2) Set respawn to an obelisk with any block underneath
3) Die
4) Notice that obelisk charge doesn't reduce unlike when the block is set to minecraft:beacon

Fix (made this change locally and built to verify it works. Not making a PR because I have other changes that may not be wanted though):
Edit **line 53** of **[common/src/main/java/com/redpxnda/respawnobelisk/data/listener/ObeliskInteraction.java](https://github.com/RedPxnda/RespawnObelisks/blob/1.20.1/common/src/main/java/com/redpxnda/respawnobelisks/data/listener/ObeliskInteraction.java#L53)** to:
`boolean isInfinite = be.getLevel().getBlockState(be.getBlockPos().below()).is(block)`

**Comment by RedPxnda** [comment]
Thanks so much, I'll try to fix this later today!

**Comment by RedPxnda** [comment]
Fixed in 2.4
