### ISSUE TITLE
[Suggestion] Add tag support for the infiniteChargeBlock config

### ISSUE THREAD

**Issue by RocketSquid** [RedPxnda/RespawnObelisks#9]
**Is your feature request related to a problem? Please describe.**
I'm helping set up a server and we would like to make it so the naturally-spawning obelisks don't run out of charges, but obelisks set up by players do unless appropriately upgraded (as in the base mod). 

**Describe the solution you'd like**
Ideally, some way to support multiple blocks for infiniteChargeBlock, either via tags or by having it be a list of blocks instead of a single one.

**Describe alternatives you've considered**
We've considered setting the infiniteChargeBlock to something unbreakable, or which does not drop itself as an item, but then either players cannot set up infinite-charge obelisks even in the very late game, or we need to create a new block or recipe.

**Comment by RedPxnda** [comment]
Good idea, thanks for your feedback. I'll add this in the next update.

**Comment by RedPxnda** [comment]
done in 2.4-c
